# Generated by Django 5.2.9 on 2025-12-16 18:31

import django.db.models.deletion
import django_ulid.models
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    django_ulid.models.ULIDField(
                        default=ulid.api.api.Api.new,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        db_index=True, help_text="Telegram user ID who owns this task"
                    ),
                ),
                ("title", models.CharField(help_text="Task title", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, default="", help_text="Task description"),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True, db_index=True, help_text="Due date for the task", null=True
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Whether the task is completed"
                    ),
                ),
                (
                    "notification_sent",
                    models.BooleanField(
                        default=False, help_text="Whether notification was sent for due date"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional category for this task",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["telegram_id", "is_completed"], name="tasks_task_telegra_2facc3_idx"
                    ),
                    models.Index(
                        fields=["due_date", "notification_sent"],
                        name="tasks_task_due_dat_ff6af5_idx",
                    ),
                ],
            },
        ),
    ]
