# Generated by Django 5.2.9 on 2025-12-16 18:31

import django_ulid.models
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    django_ulid.models.ULIDField(
                        default=ulid.api.api.Api.new,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        db_index=True, help_text="Telegram user ID who owns this category"
                    ),
                ),
                ("name", models.CharField(help_text="Category name", max_length=100)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("telegram_id", "name"), name="unique_category_per_user"
                    )
                ],
            },
        ),
    ]
